language: r

r:
  - release
  - devel

r_packages:
  - covr

after_success:
  - travis_wait 20 Rscript -e 'library(covr); codecov()'

script:
  - R CMD build .
  - travis_wait 20 R CMD check --as-cran *.tar.gz